package calculadora.postfija;

import java.util.ArrayList;
import java.util.Stack;
import java.util.StringTokenizer;

public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        setLocationRelativeTo(null);

//    String diasPunto = "2+4*2/4-5(2+5)-4";
//    String diaPuntoArray[] = diasPunto.split("");
//
//    System.out.println("--Ejemplo 2--");
//    for(String diaPunto : diaPuntoArray){
//	if(diaPunto.equals("/")){
//        System.out.println("Separa bien los signos ");
//        }else{
//            System.out.println("Hola");
//        }
//        if(diaPunto.equals("(")){
//            String parentesis = "";
//        }
//    }
//        String entrada = "2+30*50-100/3-4^3";
//       StringTokenizer st = new StringTokenizer(entrada, "+*-/-^");
    String cadena = "2+30*50-100/3-4^3";
//    String delimitadores= "[.,;?!¡¿\'\"\\[\\]]+";
//    String delimitadores= "[-+/*^\'\"\\[\\]]";
    String[] palabrasSeparadas = cadena.split("-\\+\\*\\/\\^");
//    String[] palabrasSeparadas = cadena.split("\\+\\-\\*\\/\\^");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_lista = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_lista = new javax.swing.JTextArea();
        tfEcuacion = new javax.swing.JTextField();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btPunto = new javax.swing.JButton();
        btAns = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btAC = new javax.swing.JButton();
        btMultiplicar = new javax.swing.JButton();
        btDividir = new javax.swing.JButton();
        btSumar = new javax.swing.JButton();
        btRestar = new javax.swing.JButton();
        btExponente = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btCerrarParentesis1 = new javax.swing.JButton();
        btDaS = new javax.swing.JButton();
        lista = new javax.swing.JButton();

        jLabel1.setText("Operaciones Realizadas");

        txt_lista.setColumns(20);
        txt_lista.setRows(5);
        jScrollPane1.setViewportView(txt_lista);

        javax.swing.GroupLayout v_listaLayout = new javax.swing.GroupLayout(v_lista.getContentPane());
        v_lista.getContentPane().setLayout(v_listaLayout);
        v_listaLayout.setHorizontalGroup(
            v_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_listaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(v_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addGroup(v_listaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        v_listaLayout.setVerticalGroup(
            v_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_listaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt7.setText("7");
        bt7.setMaximumSize(new java.awt.Dimension(51, 23));
        bt7.setMinimumSize(new java.awt.Dimension(51, 23));
        bt7.setPreferredSize(new java.awt.Dimension(51, 23));
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt7MouseClicked(evt);
            }
        });

        bt8.setText("8");
        bt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt8MouseClicked(evt);
            }
        });

        bt9.setText("9");
        bt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt9MouseClicked(evt);
            }
        });

        bt4.setText("4");
        bt4.setMaximumSize(new java.awt.Dimension(51, 23));
        bt4.setMinimumSize(new java.awt.Dimension(51, 23));
        bt4.setPreferredSize(new java.awt.Dimension(51, 23));
        bt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt4MouseClicked(evt);
            }
        });

        bt5.setText("5");
        bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt5MouseClicked(evt);
            }
        });

        bt6.setText("6");
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt6MouseClicked(evt);
            }
        });

        bt1.setText("1");
        bt1.setMaximumSize(new java.awt.Dimension(51, 23));
        bt1.setMinimumSize(new java.awt.Dimension(51, 23));
        bt1.setPreferredSize(new java.awt.Dimension(51, 23));
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt1MouseClicked(evt);
            }
        });

        bt2.setText("2");
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt2MouseClicked(evt);
            }
        });

        bt3.setText("3");
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt3MouseClicked(evt);
            }
        });

        bt0.setText("0");
        bt0.setMaximumSize(new java.awt.Dimension(51, 23));
        bt0.setMinimumSize(new java.awt.Dimension(51, 23));
        bt0.setPreferredSize(new java.awt.Dimension(51, 23));
        bt0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt0MouseClicked(evt);
            }
        });

        btPunto.setText(".");
        btPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPuntoMouseClicked(evt);
            }
        });

        btAns.setText("Ans");

        btDel.setText("DEL");
        btDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDelMouseClicked(evt);
            }
        });

        btAC.setText("AC");
        btAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btACMouseClicked(evt);
            }
        });

        btMultiplicar.setText("X");
        btMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMultiplicarMouseClicked(evt);
            }
        });

        btDividir.setText("/");
        btDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDividirMouseClicked(evt);
            }
        });

        btSumar.setText("+");
        btSumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSumarMouseClicked(evt);
            }
        });

        btRestar.setText("-");
        btRestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRestarMouseClicked(evt);
            }
        });

        btExponente.setText("x^");
        btExponente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExponenteMouseClicked(evt);
            }
        });

        btIgual.setText("=");
        btIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIgualMouseClicked(evt);
            }
        });

        btCerrarParentesis1.setText("S->D");
        btCerrarParentesis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCerrarParentesis1MouseClicked(evt);
            }
        });

        btDaS.setText("D->S");
        btDaS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDaSMouseClicked(evt);
            }
        });

        lista.setText("Lista ");
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEcuacion)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btDel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btExponente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCerrarParentesis1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDaS, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt8)
                    .addComponent(bt9)
                    .addComponent(btAC)
                    .addComponent(btDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt6)
                    .addComponent(bt5)
                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMultiplicar)
                    .addComponent(btDividir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3)
                    .addComponent(bt2)
                    .addComponent(btRestar)
                    .addComponent(btSumar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAns)
                    .addComponent(btPunto)
                    .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIgual)
                    .addComponent(btExponente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDaS)
                    .addComponent(btCerrarParentesis1)
                    .addComponent(lista))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIgualMouseClicked
        String ecua = tfEcuacion.getText();
        String post[] = tfEcuacion.getText().split("");
        int numero = 0;
        int cantidad = 0;
        int valor = 1;
        String[] pila = new String[post.length / 2];
        String[] lista = new String[post.length];

        for (String signos : post) {
            if (signos.equals("+") || signos.equals("-") || signos.equals("*") || signos.equals("/") || signos.equals("^")
                    || signos.equals("(") || signos.equals(")")) {
                if (numero == 0) {
                    pila[numero] = signos;
                    numero++;
                } else {
                    if ((pila[numero - 1].equals("+") || pila[numero - 1].equals("-")) && (signos.equals("+")
                            || signos.equals("-") || signos.equals("*") || signos.equals("/") || signos.equals("^")
                            || signos.equals("(") || signos.equals(")"))) {
                        pila[numero] = signos;
                        numero++;
                    } else if ((pila[numero - 1].equals("*") || pila[numero - 1].equals("/")) && (signos.equals("*")
                            || signos.equals("/") || signos.equals("^") || signos.equals("(") || signos.equals(")"))) {
                        pila[numero] = signos;
                        numero++;
                    } else {
                        for (int i = numero; i > 0; i--) {
                            lista[cantidad] = pila[i - 1];
                            cantidad++;
                        }
                        numero = 0;
                        pila[numero] = signos;
                        numero++;
                    }
                }
            } else {
                lista[cantidad] = signos;
                cantidad++;
            }
        }

        for (int i = numero; i > 0; i--) {
            lista[cantidad] = pila[i - 1];
            cantidad++;
        }

        double operador1, operador2;

        Stack<String> stack = new Stack<String>();
        for (int i = 0; i < lista.length; i++) {
            if (lista[i].contentEquals("+")) {
                operador2 = Double.parseDouble(stack.pop());
                operador1 = Double.parseDouble(stack.pop());
                res = operador1 + operador2;
                stack.push(Double.toString(res));
            } else if (lista[i].contentEquals("-")) {
                operador2 = Double.parseDouble(stack.pop());
                operador1 = Double.parseDouble(stack.pop());
                res = operador1 - operador2;
                stack.push(Double.toString(res));
            } else if (lista[i].contentEquals("*")) {
                operador2 = Double.parseDouble(stack.pop());
                operador1 = Double.parseDouble(stack.pop());
                res = operador1 * operador2;
                stack.push(Double.toString(res));
            } else if (lista[i].contentEquals("/")) {
                operador2 = Double.parseDouble(stack.pop());
                operador1 = Double.parseDouble(stack.pop());
                res = operador1 / operador2;
                stack.push(Double.toString(res));
            } else if (lista[i].contentEquals("^")) {
                operador2 = Double.parseDouble(stack.pop());
                operador1 = Double.parseDouble(stack.pop());
                res = Math.pow(operador1, operador2);
                stack.push(Double.toString(res));
            } else {
                stack.push(lista[i]);
            }
        }

        if (res - (int) res == 0) {
            ecua += " = " + (int) Double.parseDouble(stack.pop());
        } else {
            ecua += " = " + stack.pop();
        }

        tfEcuacion.setText(ecua);
        txt_lista.setText( txt_lista.getText() + tfEcuacion.getText() + "\n");
    }//GEN-LAST:event_btIgualMouseClicked

    private void bt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "7";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt7MouseClicked

    private void bt8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt8MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "8";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt8MouseClicked

    private void bt9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt9MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "9";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt9MouseClicked

    private void bt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt4MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "4";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt4MouseClicked

    private void bt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "5";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt5MouseClicked

    private void bt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "6";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt6MouseClicked

    private void bt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "1";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt1MouseClicked

    private void bt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "2";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt2MouseClicked

    private void bt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "3";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt3MouseClicked

    private void bt0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt0MouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "0";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_bt0MouseClicked

    private void btPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPuntoMouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += ".";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_btPuntoMouseClicked

    private void btMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMultiplicarMouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "*";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_btMultiplicarMouseClicked

    private void btDividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDividirMouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "/";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_btDividirMouseClicked

    private void btSumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSumarMouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "+";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_btSumarMouseClicked

    private void btRestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRestarMouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "-";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_btRestarMouseClicked

    private void btExponenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExponenteMouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion += "^";
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_btExponenteMouseClicked

    private void btDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDelMouseClicked
        String ecuacion = tfEcuacion.getText();
        ecuacion = ecuacion.substring(0, ecuacion.length());
        tfEcuacion.setText(ecuacion);
    }//GEN-LAST:event_btDelMouseClicked

    private void btACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btACMouseClicked
        tfEcuacion.setText("");
    }//GEN-LAST:event_btACMouseClicked

    private void btCerrarParentesis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCerrarParentesis1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btCerrarParentesis1MouseClicked

    private void btDaSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDaSMouseClicked
        double res2 = res;
        int contador = 0;
        while (res2 % 2 != 0) {
            System.out.println(contador);
            res2 = res2 * 10;
            contador++;
        };
        int diez = 1;
        for (int i = 0; i < contador; i++) {
            diez = diez * 10;
        }
        double nominador = res * diez;
        int nom = 0;
        if (nominador - (int) nominador == 0) {
            nom = (int) nominador;
        }
        int max = mcd (nom, diez);
        nom = nom / max;
        diez = diez / max;
        String ecu = tfEcuacion.getText();
        String [] cambio = ecu.split("=");
        cambio [1] = nom+"/"+diez;
        tfEcuacion.setText(cambio[0]+" = "+cambio[1]);      
    }//GEN-LAST:event_btDaSMouseClicked

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        v_lista.setModal(true);
        v_lista.pack();
        v_lista.setVisible(true);
        v_lista.setLocationRelativeTo(null);
    }//GEN-LAST:event_listaMouseClicked

    private int mcd(int a, int b) {
        if (b == 0) {
            return a;
        } else {
            return mcd(b, a % b);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAC;
    private javax.swing.JButton btAns;
    private javax.swing.JButton btCerrarParentesis1;
    private javax.swing.JButton btDaS;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btDividir;
    private javax.swing.JButton btExponente;
    private javax.swing.JButton btIgual;
    private javax.swing.JButton btMultiplicar;
    private javax.swing.JButton btPunto;
    private javax.swing.JButton btRestar;
    private javax.swing.JButton btSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lista;
    private javax.swing.JTextField tfEcuacion;
    private javax.swing.JTextArea txt_lista;
    private javax.swing.JDialog v_lista;
    // End of variables declaration//GEN-END:variables
    double res = 0.0;
}
